server:
  port: 8083
spring:
  application:
    name: library-pc-web

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000