server:
  port: 8084

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka

spring:
  application:
    name: library-member-service
  datasource:
      #数据库相关的配置url  -SSL连接设置为false
      url: jdbc:mysql://localhost:3306/library?serverTimezone=UTC
      #配置用户名
      username: root
      #配置密码
      password: root
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
      show-sql: true
      hibernate:
        ddl-auto: update